### ISSUE TITLE
waybackarchive: invalid control character in URL

### ISSUE THREAD

**Issue by ZeroDot1** [projectdiscovery/subfinder#159]
`waybackarchive: parse http://web.archive.org/cdx/search/cdx?url=*.coinwebmining.com/*&output=json&fl=original&collapse=urlkey&page=: net/url: invalid control character in URL`

And:
`ipv4info: <nil>`

And:
`dnsdb: Unexpected return status 503`

And:
`baidu: unexpected EOF`

Is it possible to fix the bugs in the future?

**Comment by Ice3man543** [comment]
Yep, will do them real soon. Thanks for creating the issue.

**Comment by ZeroDot1** [comment]
@Ice3man543  Thank you very much, Subfinder is one of the most used programs for my research work, and I appreciate it very much.

**Comment by BigB86** [comment]
I would like to report this issue is still happening. Will this be fixed? I also have various other issues:
`dogpile: Get https://www.dogpile.com/search/web?q=SITE.com.sg&qsi=1: EOF`

`threatcrowd: Get https://www.threatcrowd.org/searchApi/v2/domain/report/?domain=SITE.com.sg: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`
`threatminer: Get https://www.threatminer.org/getData.php?e=subdomains_container&q=SITE.com.sg&t=0&rt=10&p=1: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

`dnsdb: Get http://www.dnsdb.org/f/SITE.com.sg.dnsdb.org/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

I let it sit for about 25 minutes with the last error you see and it never went any further and had to exit out of it. As it is right now I cannot get it to go any further and I'm unable to use the tool.

**Comment by whoot** [comment]
+1 I´m also still getting the 'waybackarchive: invalid control character in URL' error

**Comment by abdilahrf** [comment]
Yes this errors seems still exists

**Comment by Ice3man543** [comment]
Hey, can you check this again if it has been fixed?

**Comment by ujjwalsinha** [comment]
Hi,
I am receiving this error with the latest version of subfinder - this is similar to one above. Please look into this.

```
Running enumeration on google.com

waybackarchive: parse http://web.archive.org/cdx/search/cdx?url=*.google.com/*&output=json&fl=original&collapse=urlkey&page=: net/url: invalid control character in URL

dnsdb: Unexpected return status 404
2019/12/10 17:03:09 panic while running job: runtime error: index out of range
panic: runtime error: index out of range [recovered]
	panic: interface conversion: interface {} is runtime.errorString, not string

goroutine 84 [running]:
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker.func1(0xc0001ac3c0)
	/root/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:61 +0x1c9
panic(0x75e8a0, 0xa96a00)
	/usr/lib/go-1.12/src/runtime/panic.go:522 +0x1b5
github.com/subfinder/subfinder/libsubfinder/sources/dnsdumpster.Query(0xc000168360, 0x2, 0x2, 0x6c7101, 0x101)
	/root/go/src/github.com/subfinder/subfinder/libsubfinder/sources/dnsdumpster/dnsdumpster.go:61 +0x14a6
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker(0xc0000acf00, 0xc0001ac3c0)
	/root/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:64 +0x6e
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).worker(0xc0000acf00, 0x14)
	/root/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:78 +0xb3
created by github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).Run
	/root/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:181 +0x7d

```

**Comment by bauthard** [comment]
Hey @ujjwalsinha, 

As per the CLI output, you are running the older version of the subfinder, please make sure to install the latest version from [here](https://github.com/projectdiscovery/subfinder#direct-installation) or download the latest binary from [here](https://github.com/projectdiscovery/subfinder/releases/tag/v2.0).

**Comment by Ice3man543** [comment]
Closing the issue now!
