### ISSUE TITLE
API keys not working for any of them. 

### ISSUE THREAD

**Issue by rajeshk28** [projectdiscovery/subfinder#253]
I have added all the required API keys but when I see the output with -v, I can not find any results from the API dependent sources. other I am able to see.

I have tried with multiple different domains but still, no one is taking the keys to give results.

Can you please post the example on the format to add keys, I am adding the same way in the screenshot given.

**Comment by bauthard** [comment]
An example is included in the project https://github.com/projectdiscovery/subfinder/blob/master/config.yaml, do you have a question for any specific source?

**Comment by skynet594** [comment]
@bauthard 
i think you are getting this error because of the path to the config.yal file that contains the API keys.
In the installation instructions it says you would have to put it to this path "$HOME/.config/subfinder/config.yaml" of your home directory. 
I had the same problem sometime ago but i solved it manually by enabling show all hidden directories in my Home directory.
Then i created a directory called .config. Inside the .config directory i created another directory called subfinder but without the dot symbol before it. the dot symbol before the config just means it's a hidden directory.
The last thing i did is to copy the .config.yal file into the subfinder directory so i had something like this .config/subfinder/config.yal
Hope this helps anyways which OS are you using??

**Comment by rajeshk28** [comment]
Ok thanks, that was helpful
